import '/imports/api/Companies/methods'
import '/imports/api/Companies/pubs'
import '/imports/api/Students/methods'
import '/imports/api/Students/pubs'
import '/imports/api/XternClasses/methods'
import '/imports/api/XternClasses/pubs'